# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import agent_zero_pb2 as agent__zero__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in agent_zero_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AgentZeroServiceStub(object):
    """Main Agent Zero gRPC service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecuteFunction = channel.unary_unary(
                '/agent_zero.AgentZeroService/ExecuteFunction',
                request_serializer=agent__zero__pb2.FunctionRequest.SerializeToString, # type: ignore
                response_deserializer=agent__zero__pb2.FunctionResponse.FromString, # type: ignore
                _registered_method=True)
        self.ExecuteFunctionStream = channel.unary_stream(
                '/agent_zero.AgentZeroService/ExecuteFunctionStream',
                request_serializer=agent__zero__pb2.FunctionRequest.SerializeToString, # type: ignore
                response_deserializer=agent__zero__pb2.FunctionStreamResponse.FromString, # type: ignore
                _registered_method=True)
        self.HandleRFC = channel.unary_unary(
                '/agent_zero.AgentZeroService/HandleRFC',
                request_serializer=agent__zero__pb2.RFCRequest.SerializeToString, # type: ignore
                response_deserializer=agent__zero__pb2.RFCResponse.FromString, # type: ignore
                _registered_method=True)
        self.ReadFile = channel.unary_unary(
                '/agent_zero.AgentZeroService/ReadFile',
                request_serializer=agent__zero__pb2.ReadFileRequest.SerializeToString, # type: ignore
                response_deserializer=agent__zero__pb2.ReadFileResponse.FromString, # type: ignore
                _registered_method=True)
        self.WriteFile = channel.unary_unary(
                '/agent_zero.AgentZeroService/WriteFile',
                request_serializer=agent__zero__pb2.WriteFileRequest.SerializeToString, # type: ignore
                response_deserializer=agent__zero__pb2.WriteFileResponse.FromString, # type: ignore
                _registered_method=True)
        self.DeleteFile = channel.unary_unary(
                '/agent_zero.AgentZeroService/DeleteFile',
                request_serializer=agent__zero__pb2.DeleteFileRequest.SerializeToString, # type: ignore
                response_deserializer=agent__zero__pb2.DeleteFileResponse.FromString, # type: ignore
                _registered_method=True)
        self.ListDirectory = channel.unary_unary(
                '/agent_zero.AgentZeroService/ListDirectory',
                request_serializer=agent__zero__pb2.ListDirectoryRequest.SerializeToString, # type: ignore
                response_deserializer=agent__zero__pb2.ListDirectoryResponse.FromString, # type: ignore
                _registered_method=True)
        self.FileExists = channel.unary_unary(
                '/agent_zero.AgentZeroService/FileExists',
                request_serializer=agent__zero__pb2.FileExistsRequest.SerializeToString, # type: ignore
                response_deserializer=agent__zero__pb2.FileExistsResponse.FromString, # type: ignore
                _registered_method=True)
        self.CreateDirectory = channel.unary_unary(
                '/agent_zero.AgentZeroService/CreateDirectory',
                request_serializer=agent__zero__pb2.CreateDirectoryRequest.SerializeToString, # type: ignore
                response_deserializer=agent__zero__pb2.CreateDirectoryResponse.FromString, # type: ignore
                _registered_method=True)
        self.MoveFile = channel.unary_unary(
                '/agent_zero.AgentZeroService/MoveFile',
                request_serializer=agent__zero__pb2.MoveFileRequest.SerializeToString, # type: ignore
                response_deserializer=agent__zero__pb2.MoveFileResponse.FromString, # type: ignore
                _registered_method=True)
        self.CopyFile = channel.unary_unary(
                '/agent_zero.AgentZeroService/CopyFile',
                request_serializer=agent__zero__pb2.CopyFileRequest.SerializeToString, # type: ignore
                response_deserializer=agent__zero__pb2.CopyFileResponse.FromString, # type: ignore
                _registered_method=True)
        self.ExecuteCommand = channel.unary_unary(
                '/agent_zero.AgentZeroService/ExecuteCommand',
                request_serializer=agent__zero__pb2.CommandRequest.SerializeToString, # type: ignore
                response_deserializer=agent__zero__pb2.CommandResponse.FromString, # type: ignore
                _registered_method=True)
        self.ExecuteCommandStream = channel.unary_stream(
                '/agent_zero.AgentZeroService/ExecuteCommandStream',
                request_serializer=agent__zero__pb2.CommandRequest.SerializeToString, # type: ignore
                response_deserializer=agent__zero__pb2.CommandStreamResponse.FromString, # type: ignore
                _registered_method=True)
        self.GetHealth = channel.unary_unary(
                '/agent_zero.AgentZeroService/GetHealth',
                request_serializer=agent__zero__pb2.HealthRequest.SerializeToString, # type: ignore
                response_deserializer=agent__zero__pb2.HealthResponse.FromString, # type: ignore
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/agent_zero.AgentZeroService/GetStatus',
                request_serializer=agent__zero__pb2.StatusRequest.SerializeToString, # type: ignore
                response_deserializer=agent__zero__pb2.StatusResponse.FromString, # type: ignore
                _registered_method=True)
        self.Ping = channel.unary_unary(
                '/agent_zero.AgentZeroService/Ping',
                request_serializer=agent__zero__pb2.PingRequest.SerializeToString, # type: ignore
                response_deserializer=agent__zero__pb2.PingResponse.FromString, # type: ignore
                _registered_method=True)


class AgentZeroServiceServicer(object):
    """Main Agent Zero gRPC service
    """

    def ExecuteFunction(self, request, context):
        """Execute a function call
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteFunctionStream(self, request, context):
        """Execute a function call with streaming response
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HandleRFC(self, request, context):
        """Handle RFC calls
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadFile(self, request, context):
        """File system operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDirectory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FileExists(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateDirectory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MoveFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CopyFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteCommand(self, request, context):
        """System operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteCommandStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHealth(self, request, context):
        """Health and monitoring
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ping(self, request, context):
        """Utility operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentZeroServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExecuteFunction': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteFunction,
                    request_deserializer=agent__zero__pb2.FunctionRequest.FromString, # type: ignore
                    response_serializer=agent__zero__pb2.FunctionResponse.SerializeToString, # type: ignore
            ),
            'ExecuteFunctionStream': grpc.unary_stream_rpc_method_handler(
                    servicer.ExecuteFunctionStream,
                    request_deserializer=agent__zero__pb2.FunctionRequest.FromString, # type: ignore
                    response_serializer=agent__zero__pb2.FunctionStreamResponse.SerializeToString, # type: ignore
            ),
            'HandleRFC': grpc.unary_unary_rpc_method_handler(
                    servicer.HandleRFC,
                    request_deserializer=agent__zero__pb2.RFCRequest.FromString, # type: ignore
                    response_serializer=agent__zero__pb2.RFCResponse.SerializeToString, # type: ignore
            ),
            'ReadFile': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadFile,
                    request_deserializer=agent__zero__pb2.ReadFileRequest.FromString, # type: ignore
                    response_serializer=agent__zero__pb2.ReadFileResponse.SerializeToString, # type: ignore
            ),
            'WriteFile': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteFile,
                    request_deserializer=agent__zero__pb2.WriteFileRequest.FromString, # type: ignore
                    response_serializer=agent__zero__pb2.WriteFileResponse.SerializeToString, # type: ignore
            ),
            'DeleteFile': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteFile,
                    request_deserializer=agent__zero__pb2.DeleteFileRequest.FromString, # type: ignore
                    response_serializer=agent__zero__pb2.DeleteFileResponse.SerializeToString, # type: ignore
            ),
            'ListDirectory': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDirectory,
                    request_deserializer=agent__zero__pb2.ListDirectoryRequest.FromString, # type: ignore
                    response_serializer=agent__zero__pb2.ListDirectoryResponse.SerializeToString, # type: ignore
            ),
            'FileExists': grpc.unary_unary_rpc_method_handler(
                    servicer.FileExists,
                    request_deserializer=agent__zero__pb2.FileExistsRequest.FromString, # type: ignore
                    response_serializer=agent__zero__pb2.FileExistsResponse.SerializeToString, # type: ignore
            ),
            'CreateDirectory': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateDirectory,
                    request_deserializer=agent__zero__pb2.CreateDirectoryRequest.FromString, # type: ignore
                    response_serializer=agent__zero__pb2.CreateDirectoryResponse.SerializeToString, # type: ignore
            ),
            'MoveFile': grpc.unary_unary_rpc_method_handler(
                    servicer.MoveFile,
                    request_deserializer=agent__zero__pb2.MoveFileRequest.FromString, # type: ignore
                    response_serializer=agent__zero__pb2.MoveFileResponse.SerializeToString, # type: ignore
            ),
            'CopyFile': grpc.unary_unary_rpc_method_handler(
                    servicer.CopyFile,
                    request_deserializer=agent__zero__pb2.CopyFileRequest.FromString, # type: ignore
                    response_serializer=agent__zero__pb2.CopyFileResponse.SerializeToString, # type: ignore
            ),
            'ExecuteCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteCommand,
                    request_deserializer=agent__zero__pb2.CommandRequest.FromString, # type: ignore
                    response_serializer=agent__zero__pb2.CommandResponse.SerializeToString, # type: ignore
            ),
            'ExecuteCommandStream': grpc.unary_stream_rpc_method_handler(
                    servicer.ExecuteCommandStream,
                    request_deserializer=agent__zero__pb2.CommandRequest.FromString, # type: ignore
                    response_serializer=agent__zero__pb2.CommandStreamResponse.SerializeToString, # type: ignore
            ),
            'GetHealth': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHealth,
                    request_deserializer=agent__zero__pb2.HealthRequest.FromString, # type: ignore
                    response_serializer=agent__zero__pb2.HealthResponse.SerializeToString, # type: ignore
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=agent__zero__pb2.StatusRequest.FromString, # type: ignore
                    response_serializer=agent__zero__pb2.StatusResponse.SerializeToString, # type: ignore
            ),
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=agent__zero__pb2.PingRequest.FromString, # type: ignore
                    response_serializer=agent__zero__pb2.PingResponse.SerializeToString, # type: ignore
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agent_zero.AgentZeroService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('agent_zero.AgentZeroService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentZeroService(object):
    """Main Agent Zero gRPC service
    """

    @staticmethod
    def ExecuteFunction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary( # type: ignore
            request,
            target,
            '/agent_zero.AgentZeroService/ExecuteFunction',
            agent__zero__pb2.FunctionRequest.SerializeToString, # type: ignore
            agent__zero__pb2.FunctionResponse.FromString, # type: ignore
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteFunctionStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream( # type: ignore
            request,
            target,
            '/agent_zero.AgentZeroService/ExecuteFunctionStream',
            agent__zero__pb2.FunctionRequest.SerializeToString, # type: ignore
            agent__zero__pb2.FunctionStreamResponse.FromString, # type: ignore
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HandleRFC(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary( # type: ignore
            request,
            target,
            '/agent_zero.AgentZeroService/HandleRFC',
            agent__zero__pb2.RFCRequest.SerializeToString, # type: ignore
            agent__zero__pb2.RFCResponse.FromString, # type: ignore
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary( # type: ignore
            request,
            target,
            '/agent_zero.AgentZeroService/ReadFile',
            agent__zero__pb2.ReadFileRequest.SerializeToString, # type: ignore
            agent__zero__pb2.ReadFileResponse.FromString, # type: ignore
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WriteFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary( # type: ignore
            request,
            target,
            '/agent_zero.AgentZeroService/WriteFile',
            agent__zero__pb2.WriteFileRequest.SerializeToString, # type: ignore
            agent__zero__pb2.WriteFileResponse.FromString, # type: ignore
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary( # type: ignore
            request,
            target,
            '/agent_zero.AgentZeroService/DeleteFile',
            agent__zero__pb2.DeleteFileRequest.SerializeToString, # type: ignore
            agent__zero__pb2.DeleteFileResponse.FromString, # type: ignore
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDirectory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary( # type: ignore
            request,
            target,
            '/agent_zero.AgentZeroService/ListDirectory',
            agent__zero__pb2.ListDirectoryRequest.SerializeToString, # type: ignore
            agent__zero__pb2.ListDirectoryResponse.FromString, # type: ignore
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FileExists(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary( # type: ignore
            request,
            target,
            '/agent_zero.AgentZeroService/FileExists',
            agent__zero__pb2.FileExistsRequest.SerializeToString, # type: ignore
            agent__zero__pb2.FileExistsResponse.FromString, # type: ignore
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateDirectory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary( # type: ignore
            request,
            target,
            '/agent_zero.AgentZeroService/CreateDirectory',
            agent__zero__pb2.CreateDirectoryRequest.SerializeToString, # type: ignore
            agent__zero__pb2.CreateDirectoryResponse.FromString, # type: ignore
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MoveFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary( # type: ignore
            request,
            target,
            '/agent_zero.AgentZeroService/MoveFile',
            agent__zero__pb2.MoveFileRequest.SerializeToString, # type: ignore
            agent__zero__pb2.MoveFileResponse.FromString, # type: ignore
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CopyFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary( # type: ignore
            request,
            target,
            '/agent_zero.AgentZeroService/CopyFile',
            agent__zero__pb2.CopyFileRequest.SerializeToString, # type: ignore
            agent__zero__pb2.CopyFileResponse.FromString, # type: ignore
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary( # type: ignore
            request,
            target,
            '/agent_zero.AgentZeroService/ExecuteCommand',
            agent__zero__pb2.CommandRequest.SerializeToString, # type: ignore
            agent__zero__pb2.CommandResponse.FromString, # type: ignore
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteCommandStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream( # type: ignore
            request,
            target,
            '/agent_zero.AgentZeroService/ExecuteCommandStream',
            agent__zero__pb2.CommandRequest.SerializeToString, # type: ignore
            agent__zero__pb2.CommandStreamResponse.FromString, # type: ignore
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetHealth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary( # type: ignore
            request,
            target,
            '/agent_zero.AgentZeroService/GetHealth',
            agent__zero__pb2.HealthRequest.SerializeToString, # type: ignore
            agent__zero__pb2.HealthResponse.FromString, # type: ignore
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary( # type: ignore
            request,
            target,
            '/agent_zero.AgentZeroService/GetStatus',
            agent__zero__pb2.StatusRequest.SerializeToString, # type: ignore
            agent__zero__pb2.StatusResponse.FromString, # type: ignore
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary( # type: ignore
            request,
            target,
            '/agent_zero.AgentZeroService/Ping',
            agent__zero__pb2.PingRequest.SerializeToString, # type: ignore
            agent__zero__pb2.PingResponse.FromString, # type: ignore
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
